"""DocuVerity examination pipeline.

examine_case(case) runs the full workflow:
    PDF metadata (optional) -> merge with examiner findings -> LR evaluation
    -> anomaly classification -> standards mapping -> recommended further checks
render_report(case, result) turns the result into a court-style draft report.
"""
from __future__ import annotations

from datetime import date
from pathlib import Path

from evaluation import classify, evaluate
from indicators import CATEGORIES, DOCUMENT_TYPES, INDICATORS, checklist_for
from pdf_metadata import analyze_pdf
from standards import standards_for

HIGH_VALUE_LR = 10.0
REPORTS_DIR = Path(__file__).resolve().parents[2] / "reports"


def merge_findings(examiner: list[dict], machine: list[dict]) -> list[dict]:
    """Examiner findings take precedence over machine-derived ones for the same indicator."""
    merged = {f["indicator"]: f for f in machine}
    merged.update({f["indicator"]: f for f in examiner})
    return list(merged.values())


def recommended_examinations(document_type: str, findings: list[dict]) -> list[dict]:
    examined = {f["indicator"] for f in findings}
    recs = []
    for item in checklist_for(document_type):
        ind = INDICATORS[item["indicator"]]
        if ind.id not in examined and ind.lr_present >= HIGH_VALUE_LR:
            recs.append({"indicator": ind.id, "question": ind.question,
                         "why": f"High diagnostic value (LR {ind.lr_present:g} if present) and not yet examined"})
    return recs


def examine_case(case: dict) -> dict:
    document_type = case.get("document_type", "generic")
    pdf_report = None
    machine_findings: list[dict] = []
    if case.get("pdf_file"):
        pdf_report = analyze_pdf(
            case["pdf_file"],
            stated_issue_date=case.get("stated_issue_date", ""),
            expected_producer=case.get("expected_producer", ""),
            generated_on_demand=case.get("generated_on_demand", False),
        )
        machine_findings = pdf_report["findings"]

    image_report = None
    if case.get("image_file"):
        from image_checker import analyze_image
        image_report = analyze_image(case["image_file"])
        if "error" in image_report:
            raise ValueError(f"Could not read image: {image_report['error']}")
        machine_findings = machine_findings + image_report["findings"]

    findings = merge_findings(case.get("findings", []), machine_findings)
    evaluation = evaluate(findings)
    categories = sorted({INDICATORS[c.indicator].category for c in evaluation.contributions if c.lr > 1})

    return {
        "case_id": case.get("case_id", "UNSPECIFIED"),
        "document_type": document_type,
        "findings": findings,
        "pdf_metadata": pdf_report,
        "image_analysis": image_report,
        "evaluation": evaluation.to_dict(),
        "classification": classify(evaluation),
        "standards": standards_for(categories),
        "recommended_examinations": recommended_examinations(document_type, findings),
    }


def _summary(result: dict) -> str:
    ev = result["evaluation"]
    cls = result["classification"]
    present = [c for c in ev["contributions"] if c["status"] == "present"]
    absent = [c for c in ev["contributions"] if c["status"] == "absent"]
    parts = [
        f"{len(present) + len(absent)} examinations were recorded: {len(present)} anomalies found "
        f"and {len(absent)} checks with no anomaly.",
        f"The combined likelihood ratio is approximately {ev['combined_lr']:,.1f} "
        f"(log10 LR {ev['combined_log10_lr']:+.2f}). {ev['verbal_conclusion']}",
    ]
    if cls["primary_mechanism"]:
        parts.append(f"The findings are most consistent with: {cls['anomaly_type'].lower()}.")
    if result["recommended_examinations"]:
        parts.append(f"{len(result['recommended_examinations'])} high-value examination(s) are "
                     f"recommended before the opinion is finalised.")
    return " ".join(parts)


def render_report(case: dict, result: dict, summary: str | None = None) -> str:
    ev = result["evaluation"]
    cls = result["classification"]
    examiner = case.get("examiner", {})
    doc_label = DOCUMENT_TYPES.get(result["document_type"], DOCUMENT_TYPES["generic"])["label"]
    pdf = result["pdf_metadata"]

    L = [
        "# Forensic Document Examination Report",
        "",
        "> **DRAFT** - generated by DocuVerity. Not valid until reviewed, amended as necessary "
        "and signed by the reporting examiner.",
        "",
        "| Field | Detail |",
        "|---|---|",
        f"| Case ID | {result['case_id']} |",
        f"| Report date | {date.today().isoformat()} |",
        f"| Examiner | {examiner.get('name', 'TBD')}, {examiner.get('designation', '')} |",
        f"| Submitting agency | {case.get('submitted_by', 'TBD')} |",
        f"| Document type | {doc_label} |",
        f"| Item description | {case.get('document_description', '')} |",
        f"| Stated issue date | {case.get('stated_issue_date', 'Not stated')} |",
    ]
    if pdf:
        L.append(f"| Electronic file | {pdf['file']} ({pdf['size_bytes']:,} bytes) |")
        L.append(f"| SHA-256 | `{pdf['sha256']}` |")

    L += ["", "## 1. Summary", "", summary or _summary(result), "",
          "## 2. Propositions", "",
          "- **Hp:** The questioned document is forged or has been altered.",
          "- **Hd:** The questioned document is genuine and unaltered.", "",
          "## 3. Examinations Performed", "",
          "| Category | Examination | Result | Confidence | Note |",
          "|---|---|---|---|---|"]
    for c in ev["contributions"]:
        result_txt = "Anomaly observed" if c["status"] == "present" else "No anomaly"
        L.append(f"| {c['category']} | {c['label']} | {result_txt} | {c['confidence']} | {c['note']} |")

    if pdf:
        L += ["", "## 4. Electronic File Examination", "",
              f"- Revisions in file: **{pdf['revisions']}**" + (" (linearized)" if pdf["linearized"] else ""),
              f"- Digital signature present: {'yes' if pdf['has_digital_signature'] else 'no'}",
              f"- Producer: {pdf['info'].get('Producer', '-')}; Creator: {pdf['info'].get('Creator', '-')}",
              f"- CreationDate: {pdf['info'].get('CreationDate', '-')}; ModDate: {pdf['info'].get('ModDate', '-')}"]
        if len(pdf["info_history"]) > 1:
            L.append("- Metadata history across revisions:")
            for i, h in enumerate(pdf["info_history"], 1):
                L.append(f"  - Revision {i}: Producer '{h.get('Producer', '-')}', ModDate {h.get('ModDate', '-')}")
        for n in pdf["notes"]:
            L.append(f"- Note: {n}")

    L += ["", "## 5. Evaluation", "",
          "Each finding is assigned a likelihood ratio (LR): how much more probable the finding is if "
          "the document is forged than if it is genuine. Correlated findings within the same category "
          "are damped (strongest counts fully, each further one at half the previous weight).", "",
          "| Finding | Result | LR | Weight | log10 contribution |",
          "|---|---|---|---|---|"]
    for c in ev["contributions"]:
        L.append(f"| {c['label']} | {c['status']} | {c['lr']:g} | {c['damping_weight']:g} | "
                 f"{c['log10_contribution']:+.2f} |")
    L += ["", f"**Combined LR:** {ev['combined_lr']:,.2f} (log10 {ev['combined_log10_lr']:+.2f}). "
          f"**Triage score** (neutral prior, for case prioritisation only): {ev['triage_score']}/100.", "",
          "## 6. Classification of Anomaly", "",
          f"**{cls['anomaly_type']}**", ""]
    for m in ev["mechanisms"]:
        L.append(f"- {m['description']} (log10 support {m['log10_support']:+.2f})")

    L += ["", "## 7. Conclusion", "", ev["verbal_conclusion"], "",
          "## 8. Recommended Further Examinations", ""]
    if result["recommended_examinations"]:
        for r in result["recommended_examinations"]:
            L.append(f"- {r['question']} _({r['why']})_")
    else:
        L.append("- None - all high-value examinations for this document type have been recorded.")

    L += ["", "## 9. Applicable Standards", ""]
    L += [f"- {s}" for s in result["standards"]["examination_standards"]]
    L += ["", "**Legal provisions (verify applicability before use):**", ""]
    L += [f"- {s}" for s in result["standards"]["legal_provisions_to_verify"]]

    L += ["", "## 10. Limitations", "",
          "- Likelihood ratios are illustrative defaults, not calibrated against casework data.",
          "- The evaluation assumes limited dependence between categories; within-category dependence "
          "is handled by damping only.",
          "- The opinion is only as reliable as the examiner's recorded observations.",
          "- Citations of standards and statutes are reference pointers and must be verified.", "",
          "## 11. Declaration", "",
          f"I, {examiner.get('name', '________________')}, have examined the item described above and "
          "the opinion expressed is my own, based on the examinations recorded in this report.", "",
          "Signature: ____________________    Date: ____________"]
    return "\n".join(L) + "\n"


def save_report(case_id: str, markdown: str, out_dir: Path | None = None) -> Path:
    out = out_dir or REPORTS_DIR
    out.mkdir(parents=True, exist_ok=True)
    safe_id = "".join(ch if ch.isalnum() or ch in "-_" else "_" for ch in case_id)
    path = out / f"{safe_id}.md"
    path.write_text(markdown, encoding="utf-8")
    return path


__all__ = ["examine_case", "render_report", "save_report", "merge_findings",
           "recommended_examinations", "CATEGORIES"]
