"""Render DocuVerity's Markdown report as a standalone, printable HTML page.

Handles the subset of Markdown the report uses: headings, blockquotes,
tables, nested bullet lists, paragraphs, **bold**, _italic_ and `code`.
All text is HTML-escaped before formatting is applied.
"""
from __future__ import annotations

import html
import re

_CSS = """
*{box-sizing:border-box}
body{margin:0;background:#eef1f5;color:#151a24;font:14px/1.6 "Segoe UI",system-ui,sans-serif;padding:24px 16px}
.page{max-width:820px;margin:0 auto;background:#fff;border:1px solid #dde2ea;border-radius:10px;padding:36px 44px}
h1{font-size:22px;margin:0 0 14px;padding-bottom:10px;border-bottom:3px solid #3558d6}
h2{font-size:16px;margin:26px 0 8px;padding-bottom:4px;border-bottom:1px solid #dde2ea;color:#1d2f73}
p{margin:6px 0}
blockquote{margin:10px 0;padding:8px 12px;background:#fff6e0;border-left:4px solid #d69a00;border-radius:4px}
.tw{overflow-x:auto;margin:8px 0}
table{border-collapse:collapse;width:100%;font-size:13px}
th,td{border:1px solid #dde2ea;padding:6px 8px;text-align:left;vertical-align:top}
th{background:#f3f5f9}
tr.flag td{background:#fdeceb}
tr.clean td{background:#eef8f1}
ul{margin:6px 0;padding-left:22px}
code{background:#f3f5f9;padding:1px 5px;border-radius:4px;font-size:12px;word-break:break-all}
.foot{margin-top:28px;font-size:11px;color:#6b7383;text-align:center}
@media (max-width:600px){.page{padding:20px 16px}}
@media print{body{background:#fff;padding:0}.page{border:none;padding:0;max-width:none}h2{break-after:avoid}tr{break-inside:avoid}}
"""


def _inline(text: str) -> str:
    out = html.escape(text, quote=False)
    out = re.sub(r"`([^`]+)`", r"<code>\1</code>", out)
    out = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", out)
    out = re.sub(r"(?<!\w)_(.+?)_(?!\w)", r"<em>\1</em>", out)
    return out


def _cells(line: str) -> list[str]:
    return [c.strip() for c in line.strip().strip("|").split("|")]


def _row_class(cells: list[str]) -> str:
    joined = " ".join(cells).lower()
    if "anomaly observed" in joined or re.search(r"\|\s*present\s*\|", "|" + "|".join(cells).lower() + "|"):
        return ' class="flag"'
    if "no anomaly" in joined or re.search(r"\|\s*absent\s*\|", "|" + "|".join(cells).lower() + "|"):
        return ' class="clean"'
    return ""


def markdown_to_html(md: str) -> str:
    lines = md.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        line = lines[i]
        if not line.strip():
            i += 1
        elif line.startswith("# "):
            out.append(f"<h1>{_inline(line[2:])}</h1>")
            i += 1
        elif line.startswith("## "):
            out.append(f"<h2>{_inline(line[3:])}</h2>")
            i += 1
        elif line.startswith("> "):
            out.append(f"<blockquote>{_inline(line[2:])}</blockquote>")
            i += 1
        elif line.lstrip().startswith("|"):
            rows = []
            while i < len(lines) and lines[i].lstrip().startswith("|"):
                rows.append(lines[i])
                i += 1
            header, body = _cells(rows[0]), [r for r in rows[1:] if not re.fullmatch(r"\|?[\s:|-]+\|?", r.strip())]
            parts = ["<div class='tw'><table><thead><tr>"]
            parts += [f"<th>{_inline(c)}</th>" for c in header]
            parts.append("</tr></thead><tbody>")
            for r in body:
                cells = _cells(r)
                parts.append(f"<tr{_row_class(cells)}>" + "".join(f"<td>{_inline(c)}</td>" for c in cells) + "</tr>")
            parts.append("</tbody></table></div>")
            out.append("".join(parts))
        elif re.match(r"\s*- ", line):
            parts = ["<ul>"]
            while i < len(lines) and re.match(r"\s*- ", lines[i]):
                item = lines[i]
                if item.startswith("  "):
                    parts.append(f"<ul><li>{_inline(item.strip()[2:])}</li></ul>")
                else:
                    parts.append(f"<li>{_inline(item[2:])}</li>")
                i += 1
            parts.append("</ul>")
            out.append("".join(parts))
        else:
            para = []
            while i < len(lines) and lines[i].strip() and not re.match(r"(#|>|\s*\||\s*- )", lines[i]):
                para.append(lines[i].strip())
                i += 1
            out.append(f"<p>{_inline(' '.join(para))}</p>")
    return "\n".join(out)


def report_page(md: str, title: str) -> str:
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width, initial-scale=1'>"
        f"<title>{html.escape(title)}</title><style>{_CSS}</style></head><body>"
        f"<div class='page'>{markdown_to_html(md)}"
        "<div class='foot'>Generated by DocuVerity · Made with IBM Bob</div></div></body></html>"
    )
